### ISSUE TITLE
Unable to fetch vehicle list

### ISSUE THREAD

**Issue by ybizeul** [onokje/node-red-contrib-tesla#41]
When click the magnifier to get vehicle list, it searches forever logging this :

```
29 Jan 17:09:20 - [info] Started modified flows
Tesla API: getting access token failed, context: Error
    at getNewTokenFromApi (/data/node_modules/node-red-contrib-tesla/src/tesla.js:35:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Context cache is empty
```

**Comment by ybizeul** [comment]
I probably should get some rest... Wasn't pasting the token correctly...
